package com.chomp.wifistorymachine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import static android.R.attr.id;

/**
 * Entity mapped to table "AUDIOBOOKS_SORT".
 */
public class AudiobooksSort {

    private Long fileid;
    /** Not-null value. */
    private String filetitle;

    private String url;


    public AudiobooksSort() {
    }

    public AudiobooksSort(Long fileid) {
        this.fileid = fileid;
    }

    public AudiobooksSort(Long fileid, String filetitle,String url) {
        this.fileid = fileid;
        this.filetitle = filetitle;
        this.url=url;
    }

    public Long getFileid() {
        return fileid;
    }

    public void setFileid(Long fileid) {
        this.fileid = fileid;
    }

    /** Not-null value. */
    public String getFiletitle() {
        return filetitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFiletitle(String filetitle) {
        this.filetitle = filetitle;
    }


    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
