package com.chomp.wifistorymachine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUDIOBOOKS_LIST".
 */
public class AudiobooksList {

    private long fid;
    private String artist;
    private String spell;
    private Integer ds;
    private String n;
    private String letter;
    private String album;
    private String subfolder;

    public AudiobooksList() {
    }

    public AudiobooksList(long fid, String artist, String spell, Integer ds, String n, String letter, String album, String subfolder) {
        this.fid = fid;
        this.artist = artist;
        this.spell = spell;
        this.ds = ds;
        this.n = n;
        this.letter = letter;
        this.album = album;
        this.subfolder = subfolder;
    }

    public long getFid() {
        return fid;
    }

    public void setFid(long fid) {
        this.fid = fid;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getSpell() {
        return spell;
    }

    public void setSpell(String spell) {
        this.spell = spell;
    }

    public Integer getDs() {
        return ds;
    }

    public void setDs(Integer ds) {
        this.ds = ds;
    }

    public String getN() {
        return n;
    }

    public void setN(String n) {
        this.n = n;
    }

    public String getLetter() {
        return letter;
    }

    public void setLetter(String letter) {
        this.letter = letter;
    }

    public String getAlbum() {
        return album;
    }

    public void setAlbum(String album) {
        this.album = album;
    }

    public String getSubfolder() {
        return subfolder;
    }

    public void setSubfolder(String subfolder) {
        this.subfolder = subfolder;
    }

}
