package com.chomp.wifistorymachine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AUDIOBOOKS_TYPE".
 */
public class AudiobooksType {

    private int sortid;
    /** Not-null value. */
    private String sortname;



    public AudiobooksType() {
    }

    public AudiobooksType(int sortid, String sortname) {
        this.sortid = sortid;
        this.sortname = sortname;

    }

    public int getSortid() {
        return sortid;
    }

    public void setSortid(int sortid) {
        this.sortid = sortid;
    }

    /** Not-null value. */
    public String getSortname() {
        return sortname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSortname(String sortname) {
        this.sortname = sortname;
    }




    @Override
    public boolean equals(Object arg0) {
        if (arg0 != null && arg0 instanceof AudiobooksType) {
            return this.getSortid()==((AudiobooksType) arg0).getSortid()
                    &&this.getSortname().equals(((AudiobooksType)arg0).getSortname());
        }
        return false;
    }
}
