package com.chomp.wifistorymachine.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "AUDIOBOOKS_SORT".
*/
public class AudiobooksSortDao extends AbstractDao<AudiobooksSort, Long> {

    public static final String TABLENAME = "AUDIOBOOKS_SORT";

    /**
     * Properties of entity AudiobooksSort.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property N = new Property(1, String.class, "n", false, "N");
        public final static Property url = new Property(2, String.class, "url", false, "URL");
    };


    public AudiobooksSortDao(DaoConfig config) {
        super(config);
    }
    
    public AudiobooksSortDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUDIOBOOKS_SORT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"N\" TEXT NOT NULL ," + // 1: n
                "\"url\" TEXT NOT NULL );"); // 2: album
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUDIOBOOKS_SORT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AudiobooksSort entity) {
        stmt.clearBindings();
 
        Long id = entity.getFileid();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        String Filetitle=entity.getFiletitle();
        if(Filetitle !=null){
            stmt.bindString(2, Filetitle);
        }

        String Url=entity.getUrl();
        if(Url !=null){
            stmt.bindString(3, Url);
        }

    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AudiobooksSort readEntity(Cursor cursor, int offset) {
        AudiobooksSort entity = new AudiobooksSort( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // n
            cursor.getString(offset + 2) // n
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AudiobooksSort entity, int offset) {
        entity.setFileid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFiletitle(cursor.getString(offset + 1));

     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AudiobooksSort entity, long rowId) {
        entity.setFileid(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AudiobooksSort entity) {
        if(entity != null) {
            return entity.getFileid();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
