package com.chomp.wifistorymachine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "StoryType".数据库
 */
public class StoryTypeDB {

    private Long id;
    private String fn;
    private Integer pic;
    private Integer ver;

    public StoryTypeDB() {
    }

    public StoryTypeDB(Long id) {
        this.id = id;
    }

    public StoryTypeDB(Long id, String fn, Integer pic, Integer ver) {
        this.id = id;
        this.fn = fn;
        this.pic = pic;
        this.ver = ver;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFn() {
        return fn;
    }

    public void setFn(String fn) {
        this.fn = fn;
    }

    public Integer getPic() {
        return pic;
    }

    public void setPic(Integer pic) {
        this.pic = pic;
    }

    public Integer getVer() {
        return ver;
    }

    public void setVer(Integer ver) {
        this.ver = ver;
    }

}
