package com.chomp.wifistorymachine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Story".试听db存储结构
 */
public class StoryDB {

    private Long id;
    /** Not-null value. */
    private String fn;
    private String artist;
    private String spell;
    private String type;
    private Integer ds;

    public StoryDB() {
    }

    public StoryDB(Long id) {
        this.id = id;
    }

    public StoryDB(Long id, String fn, String artist, String spell, String type, Integer ds) {
        this.id = id;
        this.fn = fn;
        this.artist = artist;
        this.spell = spell;
        this.type = type;
        this.ds = ds;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFn() {
        return fn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFn(String fn) {
        this.fn = fn;
    }

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getSpell() {
        return spell;
    }

    public void setSpell(String spell) {
        this.spell = spell;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getDs() {
        return ds;
    }

    public void setDs(Integer ds) {
        this.ds = ds;
    }

}
